# - Try to find oneDNN
#
# The following are set after configuration is done:
#  ONEDNN_FOUND          : set to true if oneDNN is found.
#  ONEDNN_INCLUDE_DIR    : path to oneDNN include dir.
#  ONEDNN_LIBRARY        : list of libraries for oneDNN
#

IF (NOT ONEDNN_FOUND)
SET(ONEDNN_FOUND OFF)

SET(ONEDNN_LIBRARY)
SET(ONEDNN_INCLUDE_DIR)
SET(DNNL_INCLUDES)

SET(ONEDNN_REQUIRED_ROOT "/data/josephku/oneDNN")
SET(ONEDNN_ROOT "${ONEDNN_REQUIRED_ROOT}" CACHE PATH "Path to oneDNN source tree" FORCE)
GET_FILENAME_COMPONENT(ONEDNN_REQUIRED_ROOT_NORMALIZED "${ONEDNN_REQUIRED_ROOT}" ABSOLUTE)
GET_FILENAME_COMPONENT(ONEDNN_ROOT_NORMALIZED "${ONEDNN_ROOT}" ABSOLUTE)
IF(NOT ONEDNN_ROOT_NORMALIZED STREQUAL ONEDNN_REQUIRED_ROOT_NORMALIZED)
  MESSAGE(FATAL_ERROR
    "oneDNN must be sourced from '${ONEDNN_REQUIRED_ROOT_NORMALIZED}', got '${ONEDNN_ROOT_NORMALIZED}'.")
ENDIF()

FIND_PATH(
  ONEDNN_INCLUDE_DIR
  NAMES oneapi/dnnl/dnnl.h oneapi/dnnl/dnnl.hpp dnnl.h dnnl.hpp
  PATHS ${ONEDNN_ROOT}
  PATH_SUFFIXES include
  NO_DEFAULT_PATH)

IF(NOT ONEDNN_INCLUDE_DIR)
  MESSAGE(FATAL_ERROR "oneDNN source files not found at '${ONEDNN_ROOT}'!")
ENDIF(NOT ONEDNN_INCLUDE_DIR)

SET(DNNL_ENABLE_PRIMITIVE_CACHE TRUE CACHE BOOL "oneDNN sycl primitive cache" FORCE)

SET(DNNL_LIBRARY_TYPE STATIC CACHE STRING "" FORCE)

SET(DNNL_CPU_RUNTIME "THREADPOOL" CACHE STRING "oneDNN cpu backend" FORCE)
SET(DNNL_GPU_RUNTIME "SYCL" CACHE STRING "oneDNN gpu backend" FORCE)
SET(DNNL_BUILD_TESTS FALSE CACHE BOOL "build with oneDNN tests" FORCE)
SET(DNNL_BUILD_EXAMPLES FALSE CACHE BOOL "build with oneDNN examples" FORCE)
SET(DNNL_ENABLE_CONCURRENT_EXEC TRUE CACHE BOOL "multi-thread primitive execution" FORCE)
SET(DNNL_EXPERIMENTAL TRUE CACHE BOOL "use one pass for oneDNN BatchNorm" FORCE)
SET(DNNL_EXPERIMENTAL_GROUPED_MEMORY ON CACHE BOOL "Enable oneDNN grouped memory / grouped GEMM support" FORCE)
SET(DNNL_EXPERIMENTAL_UKERNEL ON CACHE BOOL "Enable oneDNN experimental ukernels" FORCE)

ADD_SUBDIRECTORY(${ONEDNN_ROOT} oneDNN EXCLUDE_FROM_ALL)
SET(ONEDNN_LIBRARY ${DNNL_LIBRARY_NAME})
IF(NOT TARGET ${ONEDNN_LIBRARY})
  MESSAGE(FATAL_ERROR "Failed to include oneDNN target")
ENDIF(NOT TARGET ${ONEDNN_LIBRARY})
GET_TARGET_PROPERTY(ONEDNN_TARGET_TYPE ${ONEDNN_LIBRARY} TYPE)
IF(NOT ONEDNN_TARGET_TYPE STREQUAL "STATIC_LIBRARY")
  MESSAGE(FATAL_ERROR
    "oneDNN target '${ONEDNN_LIBRARY}' must be a static library, got '${ONEDNN_TARGET_TYPE}'.")
ENDIF()
GET_TARGET_PROPERTY(ONEDNN_TARGET_SOURCE_DIR ${ONEDNN_LIBRARY} SOURCE_DIR)
IF(NOT ONEDNN_TARGET_SOURCE_DIR)
  MESSAGE(FATAL_ERROR
    "Unable to determine oneDNN target source directory for '${ONEDNN_LIBRARY}'.")
ENDIF()
GET_FILENAME_COMPONENT(ONEDNN_TARGET_SOURCE_DIR_NORMALIZED
  "${ONEDNN_TARGET_SOURCE_DIR}" ABSOLUTE)
STRING(FIND "${ONEDNN_TARGET_SOURCE_DIR_NORMALIZED}"
  "${ONEDNN_REQUIRED_ROOT_NORMALIZED}/" _ONEDNN_TARGET_SOURCE_DIR_PREFIX)
IF(NOT ONEDNN_TARGET_SOURCE_DIR_NORMALIZED STREQUAL ONEDNN_REQUIRED_ROOT_NORMALIZED
   AND NOT _ONEDNN_TARGET_SOURCE_DIR_PREFIX EQUAL 0)
  MESSAGE(FATAL_ERROR
    "oneDNN target '${ONEDNN_LIBRARY}' must be built from '${ONEDNN_REQUIRED_ROOT_NORMALIZED}', got '${ONEDNN_TARGET_SOURCE_DIR_NORMALIZED}'.")
ENDIF()
MESSAGE(STATUS "oneDNN target: ${ONEDNN_LIBRARY} (${ONEDNN_TARGET_TYPE})")

IF(NOT APPLE AND CMAKE_COMPILER_IS_GNUCC)
  TARGET_COMPILE_OPTIONS(${ONEDNN_LIBRARY} PRIVATE -Wno-uninitialized)
  TARGET_COMPILE_OPTIONS(${ONEDNN_LIBRARY} PRIVATE -Wno-strict-overflow)
  TARGET_COMPILE_OPTIONS(${ONEDNN_LIBRARY} PRIVATE -Wno-error=strict-overflow)
ENDIF(NOT APPLE AND CMAKE_COMPILER_IS_GNUCC)

TARGET_COMPILE_OPTIONS(${ONEDNN_LIBRARY} PRIVATE -Wno-tautological-compare)
GET_TARGET_PROPERTY(DNNL_INCLUDES ${ONEDNN_LIBRARY} INCLUDE_DIRECTORIES)
TARGET_LINK_LIBRARIES(${ONEDNN_LIBRARY} PRIVATE ze_loader)
list(APPEND ONEDNN_INCLUDE_DIR ${DNNL_INCLUDES})

LIST(FILTER ONEDNN_INCLUDE_DIR EXCLUDE REGEX ".*${ONEDNN_ROOT}/third_party.*")

SET(ONEDNN_FOUND ON)
MESSAGE(STATUS "Found oneDNN: TRUE")

ENDIF(NOT ONEDNN_FOUND)
